### PR TITLE
#10

### PR DESCRIPTION
**Pull request by fransimo**
Implementation of "Social Integration: Share via Tweet / Share via Facebook #10" fixed for baker 4.3 and tested on iOs8 plus image resizing before sharing

### CODE REVIEW

**Comment by pieterclaerhout** [comment]
Hi @fransimo,

Thanks for the pull request, however, I'm missing one thing. It would be nice if you could disallow sharing of an issue by setting a property in the book.json file (or actually, have a flag to enable the sharing).

**Comment by fransimo** [comment]
OK. I'll do it by a setting.

**Comment by fransimo** [comment]
Don't merge yet. The share message is in Spanish. I'll translate it.

**Comment by fransimo** [comment]
Done, Localizated

**Pull request merged**
